name: AutoBuildAndRelease

permissions:
  contents: write
  
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create dev tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -f dev
          git push -f https://x-access-token:${{ env.TOKEN }}@github.com/MCFurina/NicoleToolbox.git dev
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish
        run: |
          dotnet restore
          dotnet publish NicoleToolbox.csproj -c Release -o publish

      - name: Zip
        run: Compress-Archive -Path publish/* -DestinationPath NicoleToolbox-Dev.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Development Build
          tag: dev
          files: NicoleToolbox-Dev.zip
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
