name: AutoBuildAndRelease

permissions:
  contents: write
  
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish-x86
        run: |
          dotnet publish NicoleToolbox.csproj -c Release -o publish-x86 -a x86 --no-self-contained /m

      - name: Zip-x86
        run: |
          $zipName = "NicoleToolbox-${{ github.run_number }}-x86.zip"
          Compress-Archive -Path publish-x86/* -DestinationPath $zipName

      - name: Release-x86
        uses: softprops/action-gh-release@v2
        with:
          name: "Dev Release #${{ github.run_number }}"
          tag_name: dev-${{ github.run_number }}
          files: NicoleToolbox-${{ github.run_number }}-x86.zip
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish-x64
        run: |
          dotnet publish NicoleToolbox.csproj -c Release -o publish-x64 -a x64 --no-self-contained /m

      - name: Zip-x64
        run: |
          $zipName = "NicoleToolbox-${{ github.run_number }}-x64.zip"
          Compress-Archive -Path publish-x64/* -DestinationPath $zipName

      - name: Release-x64
        uses: softprops/action-gh-release@v2
        with:
          name: "Dev Release #${{ github.run_number }}"
          tag_name: dev-${{ github.run_number }}
          files: NicoleToolbox-${{ github.run_number }}-x64.zip
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish-arm64
        run: |
          dotnet publish NicoleToolbox.csproj -c Release -o publish-arm64 -a arm64 --no-self-contained /m

      - name: Zip-arm64
        run: |
          $zipName = "NicoleToolbox-${{ github.run_number }}-arm64.zip"
          Compress-Archive -Path publish-arm64/* -DestinationPath $zipName

      - name: Release-arm64
        uses: softprops/action-gh-release@v2
        with:
          name: "Dev Release #${{ github.run_number }}"
          tag_name: dev-${{ github.run_number }}
          files: NicoleToolbox-${{ github.run_number }}-arm64.zip
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}